areas:
  - id: "AreaAlpha"
    world: "world"
    crystals: 5
    chunks:
      - "9,2"
      - "9,3"
      - "10,2"
      - "10,3"
  - id: "BetaZone"
    world: "world"
    crystals: 3
    chunks:
      - "5,5"
      - "6,5"
